#=======================================================================
# EventBridge SchedulerがLambda関数を実行するためのロール
#=======================================================================
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  NotionLambdaRole:
    Type: 'AWS::IAM::Role'
    Properties: 
      RoleName: 'lambda-eventbridge-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'scheduler.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'lambda-eventbridge-policy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action: 
                  - 'lambda:InvokeFunction'
                Resource: '*'